#!/bin/sh
# shader-tables.sh — GENERATE the expected-dword tables for the sovereign-encoder oracle straight out
# of `kernel/core/gpu.cyr`, so the comparison has two independent sides.
#
# ⛔⛔ WHY GENERATED AND NOT TYPED. `tests/gpu/edgeasm.cyr` states the rule at :36-40 — *"hand-copying
# and then diffing marks its own homework, because both sides would share the same mistake"* — and
# then hand-copies its own `bc_want`/`want` tables anyway. Those tables are in fact byte-identical to
# the shipped hex, so no harm has come of it yet, but the property is maintained by care rather than
# by construction. An extractor removes the care.
#
# THE TWO SIDES, STATED PLAINLY:
#   • EXPECTED  = the committed, iron-proven dwords in gpu.cyr, mechanically extracted here.
#   • EMITTED   = `kernel/shaders/emit/<name>.emit.cyr` run through mabda's encoder at test time.
# Neither is derived from the other. A mistake in an emit list cannot be cancelled by the same
# mistake in the table, which is the whole point.
#
# ⚠ WHAT THIS DOES *NOT* PROVE. Byte-identity says the emit list packs the same bits the hex does. It
# says nothing about whether either MEANS what `kernel/shaders/<name>.s` says. That direction needs a
# disassembler and neither agnos nor mabda has one; for the seven shaders in `check.sh:122` the
# llvm-mc `.s`-vs-hex gate covers it and stays.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/kernel/core/gpu.cyr"
OUT_DIR="$ROOT/tests/gpu/gen"
OUT="$OUT_DIR/oracle_tables.cyr"

[ -f "$SRC" ] || { echo "shader-tables: $SRC not found" >&2; exit 1; }
mkdir -p "$OUT_DIR"

# ⚠ MODULE-SCOPE `var X[N]` IS N x u64, NOT N BYTES — measured under this box's cycc on 2026-08-13
# (two adjacent `var a[4]`/`var b[4]` are 32 bytes apart), and consistent with the note at
# edgeasm.cyr:147. The generated tables are therefore `var <name>_want[<dwords>]` addressed with
# `store64(&t + i*8, ...)`. Cyrius's array units differ BY SCOPE — function-local `var X[N]` is N
# bytes — so this is the exact place that trap bites. Re-measure rather than assume on a pin bump.
awk '
function flush_shader(   i) {
    if (name == "") return
    if (n == 0) { printf("shader-tables: %s_write has NO store32 dwords\n", name) > "/dev/stderr"; bad = 1; return }
    # ⛔ CONTIGUITY. Every offset must be exactly 4*i counting from 0 — no gaps, no reordering, no
    # conditional stores. It holds for all 20 tables today; asserting it is what keeps this extractor
    # honest against a future `*_write` that grows an `if`. `shader-blob.sh:78` discards the offset
    # entirely when it scrapes hex, so a reordered table would be invisible there. Not here.
    for (i = 0; i < n; i++) {
        if (off[i] != i * 4) {
            printf("shader-tables: %s_write dword %d is at offset %d, expected %d -- table is not contiguous\n",
                   name, i, off[i], i * 4) > "/dev/stderr"
            bad = 1
            return
        }
    }
    # The declared return value. 13 of 20 return the DWORD count and 7 return BYTES (dwords*4); no
    # call site consumes it either way. Reported, never gated — see the note in shaderasm.cyr. A
    # value that is neither IS an error: it means the table and its own declaration disagree.
    unit = "?"
    if (ret == n)     unit = "dwords"
    if (ret == n * 4) unit = "bytes"
    if (unit == "?") {
        printf("shader-tables: %s_write returns %d but emits %d dwords (%d bytes) -- neither\n",
               name, ret, n, n * 4) > "/dev/stderr"
        bad = 1
        return
    }
    printf("var %s_want[%d];\n", name, n)
    printf("fn %s_want_fill(): i64 {\n", name)
    for (i = 0; i < n; i++) printf("    store64(&%s_want + %d * 8, 0x%s);\n", name, i, hex[i])
    printf("    return %d;\n", n)
    printf("}\n\n")
    printf("  %-14s %4d dwords (returns %d, %s)\n", name, n, ret, unit) > "/dev/stderr"
    total += n
    shaders++
}
BEGIN {
    bad = 0; total = 0; shaders = 0; name = ""; n = 0; ret = -1
    print "# GENERATED by scripts/check/shader-tables.sh — DO NOT EDIT, DO NOT COMMIT."
    print "# Expected-dword tables extracted mechanically from kernel/core/gpu.cyr. The committed hex"
    print "# is the authority; this file is only a machine-readable view of it."
    print ""
}
/^fn [a-z0-9_]+_write\(dst_phys\)/ {
    flush_shader()
    name = $2
    sub(/_write\(dst_phys\).*/, "", name)
    n = 0; ret = -1
    next
}
# A closing brace in column 0 ends the function body.
/^}/ { flush_shader(); name = ""; next }
name != "" && /^[[:space:]]*store32\(dst_phys \+ [0-9]+,[[:space:]]*0x[0-9a-fA-F]+\);/ {
    line = $0
    sub(/.*store32\(dst_phys \+ /, "", line)
    o = line + 0
    sub(/^[0-9]+,[[:space:]]*0x/, "", line)
    sub(/\).*/, "", line)
    sub(/;.*/, "", line)
    off[n] = o
    hex[n] = line
    n++
    next
}
name != "" && /^[[:space:]]*return [0-9]+;/ {
    r = $0
    sub(/.*return /, "", r)
    sub(/;.*/, "", r)
    ret = r + 0
    next
}
END {
    flush_shader()
    printf("shader-tables: %d shaders, %d dwords total\n", shaders, total) > "/dev/stderr"
    if (bad) exit 1
    if (shaders == 0) { print "shader-tables: extracted NOTHING -- the fn pattern no longer matches gpu.cyr" > "/dev/stderr"; exit 1 }
}
' "$SRC" > "$OUT"

echo "shader-tables: wrote $OUT ($(wc -l < "$OUT") lines)"
