#!/bin/sh
# shader-decls.sh — GENERATE the per-shader register declarations the oracles assert against, straight
# out of `kernel/shaders/*.s`, so no oracle ever types a number it also checks.
#
# ⛔ WHY. `shaderasm.cyr` and `edgeasm.cyr` assert `ea_vgpr_check(13, ...)` / `ea_sgpr_exact(21, ...)`
# and so on. Those constants came from `.amdhsa_next_free_vgpr` / `_sgpr` in the `.s` files — but once
# TYPED they are a second copy, and a second copy drifts. `edgeasm.cyr` shipped exactly that defect
# until 1.56.44: it asserted edge_setup against 56 VGPRs under a comment claiming edge_setup and
# edge_cov "share RSRC1", when edge_setup declares 32 and ships its own `_ESET = 0x002C00C7`. A typed
# 56 sat beside a declared 32 for the whole life of the file, and no gate could see the difference
# because both sides of the comparison were written by the same hand.
#
# ⇒ The declaration is EXTRACTED. If a `.s` changes its register budget, the oracle's expectation moves
# with it in the same commit, and a mismatch becomes impossible rather than merely unlikely.
#
# ⚠ SCOPE, STATED HONESTLY: this extracts what the `.s` DECLARES. It does not know what the shader
# USES — that is the tracker's job, and the point of `ea_sgpr_exact` is to make the two meet. Nor does
# it read `gpu_regs.cyr`: mapping shader -> RSRC1 constant is done by hand in the arm functions and is
# not mechanically recoverable from either file, so a wrong mapping is still possible. Said plainly
# rather than implied away.
set -eu

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
SRC="$ROOT/kernel/shaders"
OUT_DIR="$ROOT/tests/gpu/gen"
OUT="$OUT_DIR/shader_decls.cyr"

[ -d "$SRC" ] || { echo "shader-decls: $SRC not found" >&2; exit 1; }
mkdir -p "$OUT_DIR"

{
  echo "# GENERATED by scripts/check/shader-decls.sh — DO NOT EDIT, DO NOT COMMIT."
  echo "# Register declarations extracted from kernel/shaders/*.s. The .s files are the authority."
  echo ""
} > "$OUT"

n=0
bad=0
for f in "$SRC"/*.s; do
    [ -f "$f" ] || continue
    name=$(basename "$f" .s)
    nfv=$(grep -oE '^[[:space:]]*\.amdhsa_next_free_vgpr[[:space:]]+[0-9]+' "$f" | head -1 | grep -oE '[0-9]+$' || true)
    nfs=$(grep -oE '^[[:space:]]*\.amdhsa_next_free_sgpr[[:space:]]+[0-9]+' "$f" | head -1 | grep -oE '[0-9]+$' || true)
    ieee=$(grep -oE '^[[:space:]]*\.amdhsa_ieee_mode[[:space:]]+[0-9]+' "$f" | head -1 | grep -oE '[0-9]+$' || true)
    [ -n "$ieee" ] || ieee=0

    # ⛔ REFUSE rather than default. A shader with no declaration is not "0 registers"; it is a file
    # this script did not understand, and emitting 0 would hand every oracle a budget that always
    # passes. Same `bad`-flag discipline as shader-tables.sh.
    if [ -z "$nfv" ] || [ -z "$nfs" ]; then
        echo "shader-decls: $name.s has no .amdhsa_next_free_vgpr/_sgpr — refusing to guess" >&2
        bad=1
        continue
    fi
    # llvm-mc's own measured limits on gfx90c: nfs 102 assembles, 103 is 'value out of range'.
    if [ "$nfs" -gt 102 ]; then
        echo "shader-decls: $name declares next_free_sgpr $nfs — above the gfx90c maximum of 102" >&2
        bad=1
    fi
    {
      printf 'var %s_nfv  = %s;\n' "$name" "$nfv"
      printf 'var %s_nfs  = %s;\n' "$name" "$nfs"
      printf 'var %s_ieee = %s;\n' "$name" "$ieee"
    } >> "$OUT"
    n=$((n + 1))
    printf '  %-14s nfv %-4s nfs %-4s ieee %s\n' "$name" "$nfv" "$nfs" "$ieee" >&2
done

[ "$bad" = "0" ] || { echo "shader-decls: FAILED" >&2; exit 1; }
[ "$n" -gt 0 ]   || { echo "shader-decls: extracted NOTHING — the .s directive pattern no longer matches" >&2; exit 1; }

echo "shader-decls: wrote $OUT ($n shaders)"
