#!/bin/sh
# H6 — ATOM DIV32/MUL32 unit sweep against the atom-interp.py oracle.
#
# WHY THIS EXISTS
# ---------------
# `atom_div64_32` was rewritten at 1.55.23 to a bit-by-bit UNSIGNED divide — because Cyrius `/` is SIGNED
# (x86 `cqo;idiv`) and the oracle's `val64 // src` diverges the moment the dividend's high half has its MSB
# set — and until this bite it had **never executed in any mode, on iron or otherwise**. `SetPixelClock` #12,
# which the modeset ladder's M7 rung runs, uses `DIV32_WS` x3 and `MUL32_WS` x3. Without this smoke, M7 would
# have been that divider's first execution: live, on a pipe, with a failure branch unreadable from the panel.
#
# The 27 expected values are ORACLE-DERIVED, generated by `agnosticos/scripts/atom-math-vectors.py` from the
# exact arithmetic of atom-interp.py's `op_div32` / `op_mul32`. Regenerate and re-paste into
# `kernel/core/atom.cyr` if the sweep changes.
#
# PURE ARITHMETIC — no MMIO, no VBIOS, no bytecode, no PHY. QEMU is the venue; this never needs iron.
#
# Build first: HDMI_ATOM=1 ATOM_MATH_SELFTEST=1 sh scripts/build.sh
# Requires: qemu-system-x86_64, OVMF, mtools, parted, gnoboot built.

set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GNOBOOT_ROOT="${GNOBOOT_ROOT:-$ROOT/../gnoboot}"

OVMF_CODE_CANDIDATES="/usr/share/edk2/x64/OVMF_CODE.4m.fd /usr/share/edk2/x64/OVMF_CODE.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/OVMF/OVMF_CODE_4M.fd /usr/share/qemu/OVMF_CODE.fd"
OVMF_VARS_CANDIDATES="/usr/share/edk2/x64/OVMF_VARS.4m.fd /usr/share/edk2/x64/OVMF_VARS.fd /usr/share/OVMF/OVMF_VARS.fd /usr/share/OVMF/OVMF_VARS_4M.fd /usr/share/qemu/OVMF_VARS.fd"
OVMF_CODE=""; for c in $OVMF_CODE_CANDIDATES; do [ -f "$c" ] && { OVMF_CODE="$c"; break; }; done
OVMF_VARS_SRC=""; for c in $OVMF_VARS_CANDIDATES; do [ -f "$c" ] && { OVMF_VARS_SRC="$c"; break; }; done
[ -n "$OVMF_CODE" ] && [ -n "$OVMF_VARS_SRC" ] || { echo "ERROR: OVMF firmware not found." >&2; exit 1; }
for tool in qemu-system-x86_64 mformat mmd mcopy parted; do command -v "$tool" >/dev/null 2>&1 || { echo "ERROR: '$tool' not on PATH" >&2; exit 1; }; done

GNOBOOT="$GNOBOOT_ROOT/build/BOOTX64.EFI"; AGNOS="$ROOT/build/agnos"
[ -f "$GNOBOOT" ] || { echo "ERROR: gnoboot not built at $GNOBOOT" >&2; exit 1; }
[ -f "$AGNOS" ]   || { echo "ERROR: agnos not built at $AGNOS" >&2; exit 1; }
# Verify the FLAG LANDED, not just that a build exists. A mode flag whose #define was never emitted ships a
# silent no-op — that is exactly how ATOM_DRY blacked the display twice. See
# [[feedback_ifdef_bites_name_their_build_flags]].
#
# ⚠ THIS CHECK IS NECESSARY BUT NOT SUFFICIENT, and the first run of this smoke proved it: the string below
# lives in the FUNCTION BODY, so it appears in the binary as soon as the function compiles — even if nothing
# ever CALLS it. On that run the call sat inside an unrelated `#ifdef HDA_HDMI` nest that was not set, this
# guard passed, and the sweep silently never executed. **String present is not code called.** The log
# assertions below are the real gate; keep them, and never downgrade this to a build-only check.
if ! strings "$AGNOS" | grep -q "atom: H6 selftest "; then
    echo "ERROR: kernel not built with ATOM_MATH_SELFTEST=1 — rebuild:" >&2
    echo "       HDMI_ATOM=1 ATOM_MATH_SELFTEST=1 sh scripts/build.sh" >&2
    exit 1
fi

WORK="$ROOT/build/atom-math-smoke"; LOGS="$ROOT/build/atom-math-smoke-logs"
rm -rf "$WORK" "$LOGS"; mkdir -p "$WORK" "$LOGS"
ESP="$WORK/esp.img"
dd if=/dev/zero of="$ESP" bs=1M count=64 status=none
parted -s "$ESP" mklabel gpt mkpart ESP fat32 1MiB 100% set 1 esp on
mformat -i "$ESP"@@1048576 -F
mmd -i "$ESP"@@1048576 ::EFI ::EFI/BOOT ::boot
mcopy -i "$ESP"@@1048576 "$GNOBOOT" ::EFI/BOOT/BOOTX64.EFI
mcopy -i "$ESP"@@1048576 "$AGNOS" ::boot/agnos

LOG="$LOGS/atom-math.log"
cp "$OVMF_VARS_SRC" "$WORK/vars.fd"; chmod +w "$WORK/vars.fd"
echo "=== AGNOS H6 ATOM div32/mul32 sweep (ATOM_MATH_SELFTEST, -m 256M) ==="
timeout "${QEMU_TIMEOUT:-40}" qemu-system-x86_64 \
    -machine q35 -m 256M -cpu max \
    -drive "if=pflash,format=raw,readonly=on,file=$OVMF_CODE" \
    -drive "if=pflash,format=raw,file=$WORK/vars.fd" \
    -drive "file=$ESP,format=raw,if=none,id=esp0" \
    -device "virtio-blk-pci,drive=esp0" \
    -serial stdio -display none -no-reboot 2>/dev/null > "$LOG"

echo "--- H6 lines ---"
strings "$LOG" | grep -E "atom: H6" | head -40
echo "----------------"

pass=0; fail=0
chk() { if grep -q "$1" "$LOG"; then echo "PASS: $2"; pass=$((pass+1)); else echo "FAIL: '$1' — $3"; fail=$((fail+1)); fi; }
nchk() { if grep -q "$1" "$LOG"; then echo "FAIL: '$1' present — $3"; fail=$((fail+1)); else echo "PASS: $2"; pass=$((pass+1)); fi; }

chk "atom: H6 selftest 27 passed, 0 failed" \
    "all 27 vectors match the oracle (17 DIV32 + 10 MUL32)" \
    "the sweep did not report 27/0 — read the per-case 'got/want' lines above"
chk "atom: H6 PASS div32/mul32 match the oracle" \
    "the sweep's own verdict line is PASS" \
    "verdict line absent or FAIL"
# The negative check: a per-case line only prints on a MISMATCH, so its presence is the failure signal.
nchk "atom: H6 case " \
    "no per-case mismatch line was printed" \
    "at least one vector diverged from the oracle"
chk "AGNOS shell" \
    "boot completed past the sweep (no fault)" \
    "boot did not reach shell — the sweep may have faulted the box"

echo ""
[ "$fail" -eq 0 ] && { echo "=== atom-math-smoke: $pass passed, 0 failed ==="; exit 0; }
echo "=== atom-math-smoke: $pass passed, $fail failed ==="; exit 1
