#!/bin/sh
# Run AGNOS kernel benchmarks
# Builds with benchmarks auto-running, boots on QEMU, captures output
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CYRIUS="$ROOT/../cyrius"
CYRB="$CYRIUS/build/cyrb"
CC="$CYRIUS/build/cc2"

# Check toolchain
if [ ! -x "$CC" ]; then
    echo "ERROR: Cyrius compiler not found at $CC" >&2
    echo "Build it: cd ../cyrius && sh bootstrap/bootstrap.sh" >&2
    exit 1
fi

# Patch: insert sh_cmd_bench() call before "Launching kybernet..."
KERNEL="$ROOT/kernel/agnos.cyr"
BENCH_KERNEL="/tmp/agnos_bench.cyr"
sed 's/serial_println("Launching kybernet\.\.\.", 21);/sh_cmd_bench();\nserial_println("Launching kybernet...", 21);/' "$KERNEL" > "$BENCH_KERNEL"

# Build patched kernel
echo "Building AGNOS with benchmarks..."
if [ -x "$CYRB" ]; then
    "$CYRB" build "$BENCH_KERNEL" /tmp/agnos_bench
else
    cat "$BENCH_KERNEL" | "$CC" > /tmp/agnos_bench
    chmod +x /tmp/agnos_bench
fi

# Check QEMU availability
if ! command -v qemu-system-x86_64 >/dev/null 2>&1; then
    echo "ERROR: qemu-system-x86_64 not found" >&2
    rm -f /tmp/agnos_bench /tmp/agnos_bench.cyr
    exit 1
fi

# Boot and capture serial output
echo "Booting on QEMU (15s timeout)..."
OUTPUT=$(timeout 15 qemu-system-x86_64 \
    -kernel /tmp/agnos_bench \
    -serial stdio \
    -display none \
    -no-reboot 2>/dev/null || true)

# Parse and display results
echo ""
echo "=== AGNOS Benchmarks ==="
BENCH_LINES=$(echo "$OUTPUT" | strings | grep -E "cycles/op|Kcycles|=== AGNOS|=== done" || true)

if [ -z "$BENCH_LINES" ]; then
    echo "WARNING: No benchmark output captured"
    rm -f /tmp/agnos_bench /tmp/agnos_bench.cyr
    exit 1
fi

echo "$BENCH_LINES"

# Write BENCHMARKS.md
COMMIT=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
DATE=$(date +%Y-%m-%d)
VERSION=$(cat "$ROOT/VERSION" | tr -d '[:space:]')

TABLE_ROWS=$(echo "$OUTPUT" | strings | grep -E "cycles/op|Kcycles" | sed 's/^[[:space:]]*//' | while IFS= read -r line; do
    name=$(echo "$line" | sed 's/:.*//' | sed 's/^[[:space:]]*//')
    val=$(echo "$line" | sed 's/.*: *//')
    echo "| $name | $val |"
done)

cat > "$ROOT/BENCHMARKS.md" << EOF
# AGNOS Benchmarks

> Auto-generated by \`scripts/bench.sh\` on $DATE (commit $COMMIT)

| Benchmark | Result |
|-----------|--------|
$TABLE_ROWS

## Environment

- QEMU x86_64, emulated ~1GHz
- AGNOS v$VERSION
- Measurements via rdtsc (CPU cycle counter)
EOF

echo ""
echo "Written to BENCHMARKS.md"

# Append to history CSV
if [ ! -f "$ROOT/bench-history.csv" ]; then
    echo "date,commit,benchmark,value,unit" > "$ROOT/bench-history.csv"
fi
echo "$OUTPUT" | strings | grep "cycles/op" | while IFS= read -r line; do
    name=$(echo "$line" | sed 's/:.*//' | sed 's/^[[:space:]]*//' | tr ' ' '_')
    val=$(echo "$line" | sed 's/.*: *//' | sed 's/ *cycles\/op//' | tr -d ' ')
    echo "$DATE,$COMMIT,$name,$val,cycles/op" >> "$ROOT/bench-history.csv"
done

echo "Appended to bench-history.csv"

rm -f /tmp/agnos_bench /tmp/agnos_bench.cyr
