#!/bin/sh
# gfx9-asm.sh — assemble a gfx90c compute kernel from .s into Cyrius dword tables.
#
# This ENDS hand-typed ISA hex. Every shader in gpu.cyr up to 1.55.x was transcribed by hand and verified
# against llvm-mc after the fact; gpu_regs.cyr:1033-1035 already warns that a miscounted RSRC word is
# "wrong, not slow". This script INVERTS that tool: llvm-mc was already trusted here as the verifier, so
# using it as the ASSEMBLER adds no new dependency and no new trust boundary.
#
# This is also exactly what AMD does. drivers/gpu/drm/amd/amdkfd/cwsr_trap_handler_gfx9.asm is hand-written
# GFX9 assembly, assembled offline, and checked into the Linux kernel as a hex array embedded in a driver
# with no runtime — structurally identical to agnos's situation.
#
# Usage:  scripts/gfx9-asm.sh kernel/shaders/blend.s [cyrius_symbol_name]
# Output: the .cyr dword table on stdout, plus RSRC1/RSRC2/VGPR/SGPR facts on stderr.
#
# ⚠ NON-NEGOTIABLE DIRECTIVES for any kernel .s in this tree — put them in the file, not here:
#     .amdhsa_ieee_mode 0            LLVM defaults to 1; agnos ships 0 (RSRC1 bit23 clear). A mismatch
#     .amdhsa_float_denorm_mode_32 0 changes float semantics silently, which is the worst failure mode.
# ⚠ ALWAYS -triple=amdgcn-amd-amdhsa, NEVER -arch=amdgcn. Under -arch, every .amdhsa_* directive fails with
#   "unknown directive" while plain instructions still assemble — the failure is QUIET.
set -e

SRC="$1"
NAME="${2:-$(basename "$SRC" .s)}"
[ -f "$SRC" ] || { echo "usage: $0 <kernel.s> [symbol_name]" >&2; exit 1; }

MC="${LLVM_MC:-llvm-mc}"
OC="${LLVM_OBJCOPY:-llvm-objcopy}"
command -v "$MC" >/dev/null || { echo "ERROR: $MC not found" >&2; exit 1; }
command -v "$OC" >/dev/null || { echo "ERROR: $OC not found" >&2; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

"$MC" -triple=amdgcn-amd-amdhsa -mcpu=gfx90c -filetype=obj "$SRC" -o "$TMP/k.o"

# A relocation IN .text means unresolved code agnos cannot link — hard fail. (OpenCL builtins do this:
# get_global_id() becomes s_swappc_b64 to an unresolved symbol.) Relocations in .rodata are EXPECTED and
# harmless: the .amdhsa_kernel descriptor references the kernel's own address, and we never embed .rodata.
if command -v llvm-readelf >/dev/null 2>&1; then
    if llvm-readelf -r "$TMP/k.o" 2>/dev/null | awk '
        /^Relocation section/ { intext = ($0 ~ /\.rel[a]?\.text/) }
        /^[0-9a-f]+ / { if (intext) found = 1 }
        END { exit(found ? 1 : 0) }'; then :; else
        echo "ERROR: $SRC produced relocations in .text — unresolved code agnos cannot link." >&2
        echo "       (OpenCL builtins do this. Use __builtin_amdgcn_* or plain asm.)" >&2
        exit 1
    fi
fi

"$OC" -O binary --only-section=.text "$TMP/k.o" "$TMP/k.bin"
SZ=$(wc -c < "$TMP/k.bin")
[ "$SZ" -gt 0 ] || { echo "ERROR: empty .text from $SRC" >&2; exit 1; }
[ $((SZ % 4)) -eq 0 ] || { echo "ERROR: .text is $SZ bytes, not a dword multiple" >&2; exit 1; }

# Harvest the kernel descriptor if the .s declared one: RSRC1@48, RSRC2@52 (AMDHSAKernelDescriptor.h).
# These are the constants agnos otherwise hand-derives into GPU_COMPUTE_PGM_RSRC1_* — deriving them from
# the same source that assembled the code removes the whole class of miscount bug.
if "$OC" -O binary --only-section=.rodata "$TMP/k.o" "$TMP/kd.bin" 2>/dev/null && [ -s "$TMP/kd.bin" ]; then
    R1=$(od -An -tx4 -j48 -N4 "$TMP/kd.bin" 2>/dev/null | tr -d ' \n')
    R2=$(od -An -tx4 -j52 -N4 "$TMP/kd.bin" 2>/dev/null | tr -d ' \n')
    [ -n "$R1" ] && echo "  RSRC1 = 0x$R1   (use this, do not hand-count)" >&2
    [ -n "$R2" ] && echo "  RSRC2 = 0x$R2   (USER_SGPR/TGID/LDS)" >&2
fi
echo "  .text = $SZ bytes / $((SZ / 4)) dwords" >&2

printf '# %s — GENERATED by scripts/gfx9-asm.sh from %s. DO NOT HAND-EDIT.\n' "$NAME" "$SRC"
printf '# Regenerate: sh scripts/gfx9-asm.sh %s %s\n' "$SRC" "$NAME"
printf 'fn %s_write(dst_phys) {\n' "$NAME"
i=0
od -An -tx4 -v "$TMP/k.bin" | tr ' ' '\n' | grep -v '^$' | while read -r w; do
    printf '    store32(dst_phys + %-4s 0x%s);\n' "$((i * 4))," "$w"
    i=$((i + 1))
done
printf '    return %s;\n' "$((SZ / 4))"
printf '}\n'
