#!/bin/sh
# gfx9-asm-check.sh — prove every shipped gfx90c ISA table still matches its assembler source.
#
# THE BITE THIS CLOSES. The 1.56.x shader plan's opening item (its "S0") was to make llvm-mc a SWEEP GATE
# rather than a habit. `scripts/gfx9-asm.sh` landed — it assembles `.s` -> gfx90c and harvests RSRC1/RSRC2
# from the `.amdhsa_kernel` descriptor instead of hand-counting them — but the check gate never did. So
# every shader table in `kernel/core/gpu.cyr` carries a "GENERATED ... DO NOT HAND-EDIT" banner that
# NOTHING ENFORCED. A hand-edit, a stale regeneration, or a `.s` edited without re-running the emitter would
# all ship silently.
#
# ⚠ WHY THIS MATTERS MORE THAN A NORMAL LINT. `gpu_regs.cyr:1033-1035` states the rule: a miscounted RSRC
# word is "WRONG, not slow". There is no QEMU path for any of `kernel/core/gpu.cyr` — QEMU emulates no AMD
# GFX — so a corrupted ISA table cannot fail in CI. It fails on the operator's only dev machine, as a burn.
# This script is the only thing standing between a bad dword and an iron burn.
#
# WHAT IT DOES: for each `kernel/shaders/*.s`, re-assemble via `scripts/gfx9-asm.sh` and byte-compare the
# emitted `fn <name>_write` body against the copy committed in `kernel/core/gpu.cyr`.
#
# Usage:  sh scripts/gfx9-asm-check.sh
# Exit 0 iff every table matches. Skips cleanly (exit 0) when llvm-mc is absent, so it never breaks a build
# on a box without LLVM — it reports the skip loudly rather than silently passing.
set -u
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GPU="kernel/core/gpu.cyr"
SHD="kernel/shaders"

MC="${LLVM_MC:-llvm-mc}"
if ! command -v "$MC" >/dev/null 2>&1; then
    echo "gfx9-asm-check: SKIPPED — $MC not found (install LLVM to enable this gate)"
    echo "  ⚠ the shader ISA tables in $GPU are UNVERIFIED on this box."
    exit 0
fi

[ -d "$SHD" ] || { echo "gfx9-asm-check: no $SHD directory"; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

rc=0
n=0
for src in "$SHD"/*.s; do
    [ -f "$src" ] || continue
    name="$(basename "$src" .s)"
    n=$((n + 1))

    # 1. Re-assemble from source.
    if ! sh scripts/gfx9-asm.sh "$src" "$name" > "$TMP/$name.gen" 2>"$TMP/$name.err"; then
        echo "  FAIL: $name — gfx9-asm.sh could not assemble $src"
        sed 's/^/        /' "$TMP/$name.err"
        rc=1
        continue
    fi

    # 2. Cut the committed copy out of gpu.cyr: the GENERATED banner through the closing brace.
    awk -v n="$name" '
        $0 ~ ("^# " n " — GENERATED by scripts/gfx9-asm.sh") { inblk = 1 }
        inblk { print }
        inblk && /^}$/ { exit }
    ' "$GPU" > "$TMP/$name.have"

    if [ ! -s "$TMP/$name.have" ]; then
        echo "  FAIL: $name — $src has no generated table in $GPU."
        echo "        Either it was never folded in, or its banner was edited. Regenerate with:"
        echo "          sh scripts/gfx9-asm.sh $src $name"
        rc=1
        continue
    fi

    # 3. Byte-compare. The emitter is deterministic, so any difference is real.
    if cmp -s "$TMP/$name.gen" "$TMP/$name.have"; then
        dwords=$(grep -c 'store32' "$TMP/$name.have")
        echo "  ok: $name ($dwords dwords)"
    else
        echo "  FAIL: $name — the table in $GPU does NOT match a fresh assembly of $src."
        echo "        Someone hand-edited the table, or edited the .s without regenerating. First diff:"
        diff "$TMP/$name.have" "$TMP/$name.gen" 2>/dev/null | head -8 | sed 's/^/        /'
        echo "        Fix with:  sh scripts/gfx9-asm.sh $src $name   (then paste over the block in $GPU)"
        rc=1
    fi
done

echo ""
if [ "$rc" -eq 0 ]; then
    echo "gfx9-asm-check: PASS — $n/$n shader ISA tables byte-identical to llvm-mc -mcpu=gfx90c"
else
    echo "gfx9-asm-check: FAIL — a shipped ISA table does not match its source. DO NOT BURN THIS."
fi

# ⚠ HONEST COVERAGE NOTE, and it is the reason this gate is not the whole of S0.
# Only shaders WITH a .s source are checked. The six 1.54.x compute kernels (the C2f/C2g dispatch ladder and
# the two f64 matmuls) were hand-typed as hex before scripts/gfx9-asm.sh existed and have NO .s — so they
# are NOT covered here and remain unverified against llvm-mc. Writing .s sources for them is the remaining
# half of S0. They are iron-proven by execution, which is a stronger check than assembly parity for those
# specific kernels, but it does not protect them from a future hand-edit the way this gate does.
exit $rc
